[versions]
agp = "8.6.1"
kotlin = "2.0.21"
camerax = "1.3.4"
mlkit_barcode = "17.3.0"
room = "2.6.1"
retrofit = "2.11.0"
okhttp = "4.12.0"
coreKtx = "1.13.1"      # Added
appcompat = "1.7.0"     # Added
material = "1.10.0"     # Added (version from initial context)

[libraries]
androidx-camera-core      = { module = "androidx.camera:camera-core",      version.ref = "camerax" }
androidx-camera-camera2   = { module = "androidx.camera:camera-camera2",   version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-camera-view      = { module = "androidx.camera:camera-view",      version.ref = "camerax" }
mlkit-barcode             = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit_barcode" }
room-runtime              = { module = "androidx.room:room-runtime",       version.ref = "room" }
room-ktx                  = { module = "androidx.room:room-ktx",           version.ref = "room" }
room-compiler             = { module = "androidx.room:room-compiler",      version.ref = "room" }
retrofit-core             = { module = "com.squareup.retrofit2:retrofit",         version.ref = "retrofit" }
retrofit-moshi            = { module = "com.squareup.retrofit2:converter-moshi",  version.ref = "retrofit" }
okhttp                    = { module = "com.squareup.okhttp3:okhttp",             version.ref = "okhttp" }
okhttp-logging            = { module = "com.squareup.okhttp3:logging-interceptor",version.ref = "okhttp" }
androidx-core-ktx         = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" } # Added
androidx-appcompat        = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" } # Added
google-android-material   = { group = "com.google.android.material", name = "material", version.ref = "material" } # Added

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize    = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-kapt         = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
