name: Android CI Baseline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Run lint, tests, and release build
        run: ./gradlew ciRelease --stacktrace --no-daemon

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: laurelid-release-apk
          path: app/build/outputs/apk/release/
