name: android-ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install required SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/settings.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Run unit tests
        run: ./gradlew clean test --console=plain

  ui-tests:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "UI tests are disabled by default. Enable this job when emulator testing is needed."
