name: android-ci
on:
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "build.gradle*"
      - "settings.gradle*"
      - "gradle.properties"
      - ".github/workflows/android-ci.yml"
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Prepare Android SDK
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          yes | sdkmanager --licenses
          if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/latest-2" ]; then sudo rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/latest-2"; fi
          sdkmanager --install "cmdline-tools;latest" "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build & unit test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean test --console=plain

# Optional separate job for UI tests (disabled by default). Create later.
