name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "cmdline-tools;latest" \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;36.0.0" \
            "emulator"

      - name: Configure local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Assemble release artifacts
        run: ./gradlew --no-daemon clean :app:assembleStagingDebug :app:assembleProductionDebug :app:assembleRelease

      - name: Lint and unit tests
        run: ./gradlew :app:lint test

      - name: Configuration cache smoke test
        run: ./gradlew --configuration-cache :app:assembleStagingDebug

  instrumented:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "cmdline-tools;latest" \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;36.0.0" \
            "emulator" \
            "system-images;android-34;google_apis;x86_64"

      - name: Configure local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Connected release-equivalent tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_6
          emulator-options: -no-snapshot -noaudio -no-window -gpu swiftshader_indirect
          script: ./gradlew --no-daemon connectedProductionReleaseAndroidTest --stacktrace --console=plain
