name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            cmdline-tools;latest
            platform-tools
            platforms;android-36
            build-tools;36.0.0

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Configure local.properties
        run: |
          if [ ! -f local.properties ]; then
            echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run checks
        run: ./gradlew --no-daemon :app:lint :app:detekt :app:assembleProductionDebug test
