name: android-ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/settings.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Write local.properties
        run: ./scripts/write_local_properties.sh

      - name: Run static analysis
        run: ./gradlew ciStaticAnalysis --console=plain

      - name: Run unit tests
        run: ./gradlew ciUnitTest --console=plain

      - name: Assemble release APK
        run: ./gradlew :app:assembleRelease --console=plain

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: laurelid-release-apk
          path: app/build/outputs/apk/release/*.apk
