name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Prepare Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-36
            build-tools;35.0.0
            platform-tools

      - name: Cache KSP artifacts
        uses: actions/cache@v4
        with:
          path: ~/.cache/ksp
          key: ${{ runner.os }}-ksp-${{ hashFiles('gradle/catalogs/libs.versions.toml', 'app/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-ksp-

      - name: Run lint, assemble, and unit tests
        run: ./gradlew --no-daemon --stacktrace --configuration-cache :app:lint :app:assembleStagingDebug :app:testStagingDebugUnitTest

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: app/build/reports/lint/
          if-no-files-found: warn

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testStagingDebugUnitTest/
          if-no-files-found: warn
