name: android-ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager \
            "cmdline-tools;latest" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "emulator" \
            "system-images;android-33;google_apis;x86_64"

      - name: Write local.properties
        run: ./scripts/write_local_properties.sh

      - name: Run ktlint, detekt, lint, and unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >-
            --console=plain
            ktlintCheck
            detekt
            lint
            test

      - name: Run connected Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: ./gradlew connectedAndroidTest --console=plain
          emulator-options: -no-window -no-snapshot -no-boot-anim

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-build-reports
          path: |
            **/build/reports/**
          if-no-files-found: ignore
