name: android-ci
on:
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "build.gradle*"
      - "settings.gradle*"
      - "gradle.properties"
      - ".github/workflows/android-ci.yml"
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            cmdline-tools;latest
            platform-tools
            platforms;android-35
            build-tools;35.0.0

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Configure local.properties
        run: |
          SDK_PATH="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
          if [ -z "$SDK_PATH" ]; then
            echo "Android SDK path not set" >&2
            exit 1
          fi
          cat <<PROP > local.properties
          sdk.dir=$SDK_PATH
          PROP

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build & unit test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean test --console=plain
